### ISSUE TITLE
show buttons in options

### ISSUE THREAD

**Issue by limelect** [DGH2112/Folder-Sync#1] opened 2019-01-04 15:47 UTC
![screenshot - 04_01_2019 17_39_51](https://user-images.githubusercontent.com/4199131/50696545-646c0000-1048-11e9-9956-465657346ff3.png)
![screenshot - 04_01_2019 17_40_09](https://user-images.githubusercontent.com/4199131/50696546-646c0000-1048-11e9-8f55-14f39b873778.png)
compiling with d10.2.3 could not see the add button....
Tried to put panel at bottom and alien page control to client
did not help why?
any idea?  

not using lvFoldersResize did not help

On btnEditClick(   add   if lvFolders.ItemIndex=-1 then Exit;

**Comment by DGH2112** [comment] 2019-01-04 17:18
Are these from the form designer or the running app? This is very strange
as I get the following from the running all...

![image](https://user-images.githubusercontent.com/19982149/50701248-16a1c880-1045-11e9-9e4a-8b4948571111.png)

The below is from a new instance (custom ini file)...

![image](https://user-images.githubusercontent.com/19982149/50701277-333e0080-1045-11e9-9ac8-1d2fca475164.png)

Its like the tab for the folders is way too big. If you ajust the form in
the form designer do thing update?
I can fix its by using aligned panels rather than anchors but I'd like to
understand why this is happening first.
regards
David Hoyle
https://www.davidghoyle.co.uk/WordPress/

**Comment by DGH2112** [comment] 2019-01-04 17:20
Ah, sorry replied to the email so the images are missing. I'll see if I can add them.

**Comment by DGH2112** [comment] 2019-01-04 17:29
You don't by any chance use a High DPI monitor do you?
All I'm think is that the form designer has scaled the client area of the folder tab but not the rest.

**Comment by limelect** [comment] 2019-01-05 15:22
Sorry for late response. Those pictures are running program.
On the IDE it is OK !!!.
My computer is a Lenovo W540. Nothing special.
I could scrounge the program and start from ZERO` and see where is the problem.
How ever which compiler do you compile. And can you compile on 10.2.3 ?

**Comment by limelect** [comment] 2019-01-05 15:52
Ok i found the problem why i do not know.
Put every thing on a Panel. In the FONTS too !!!
I did not touch it. Only on Folders to prove a point.
I also made some to client.
Now the buttons are visible.
Should be fixed all over with panels.
[Option.zip](https://github.com/DGH2112/Folder-Sync/files/2729626/Option.zip)

**Comment by limelect** [comment] 2019-01-05 15:54
Waiting for update

**Comment by limelect** [comment] 2019-01-05 16:06
Option update. But is should be working on.
[Option.zip](https://github.com/DGH2112/Folder-Sync/files/2729639/Option.zip)

**Comment by DGH2112** [comment] 2019-01-05 16:55
I'd still be interested in what DPI you're running as I cannot see why the anchor would be different on your machine any my (DPI = 100% not the default 125%).

**Comment by limelect** [comment] 2019-01-05 17:19
![screenshot - 05_01_2019 19_19_53](https://user-images.githubusercontent.com/4199131/50727105-bbdc9f80-111e-11e9-8c34-de4162eb12c9.png)

**Comment by limelect** [comment] 2019-01-05 17:21
Will the above do?  As i got the computer from day 1.Never changed

**Comment by DGH2112** [comment] 2019-01-05 17:25
Please click on the link "Make text and other items larger or smaller" to see the DPI setting.

**Comment by limelect** [comment] 2019-01-05 17:28
![screenshot - 05_01_2019 19_19_53](https://user-images.githubusercontent.com/4199131/50727187-1b877a80-1120-11e9-9ff6-a39f0a384195.png)

**Comment by limelect** [comment] 2019-01-05 17:30
The program should not be dependent on screen resolution since there are so many
computers out there.

**Comment by DGH2112** [comment] 2019-01-05 17:30
Yep, that what I thought the problem is. You running at 125% and the IDE is NOT High DPI aware. I've tried to get on to Quality Portal to see if there is an existing QP for this but its down at the moment.

**Comment by limelect** [comment] 2019-01-05 17:32
Why not add panels and done with it? simple. do not bother with screen

**Comment by DGH2112** [comment] 2019-01-05 17:33
You could go in the the Project Options dialogue and click on the "Enabled High DPI" under the Application node to see if that makes a difference?
This is an old application and I haven't done anything in it for multiple monitors, High DPI, etc. Note: DPI support in 10.2.3 is limited / broken but 10.3 is supported to be better.

**Comment by DGH2112** [comment] 2019-01-05 17:39
If it turns out the anchors in the IDE / App are broken by DPI > 100% then yes, I'll have to change it _(and many other applications)_. I would like to check QP before embarking on this journey as there may be another workaround.

Note: It will affect anyone trying to right align controls on a form, like OK and Cancel buttons even if they use panels unless they use A LOT of panels, one each for the bottom and right anchors.

**Comment by limelect** [comment] 2019-01-05 17:42
No it did not help to Enabled High DPI

**Comment by limelect** [comment] 2019-01-05 17:47
I never had such a problem although i have many Delphi programs.
See a small list here http://limelect.com/free-programs/ 
and all the professional one never head  that problem.
P.S my last program mite interest you?
http://limelect.com/downloads/explorer-list/

**Comment by DGH2112** [comment] 2019-01-05 17:50
Looking more closely at the screen shots it seems it might be isolated to tabsheets.

I don't have any time to change this today, I'll look at it tomorrow.

**Comment by limelect** [comment] 2019-01-05 17:52
O.K when ever

**Comment by DGH2112** [comment] 2019-01-05 21:32
I've upload some changes which should hopefully fix your issues with the buttons in the options dialogue not being visible. Let me know if this works and I can then close this issue.

**Comment by limelect** [comment] 2019-01-06 06:12
It is OK. I see you are using the panels for a solution.
Right?
On the fonts tab there is no panel. 
I wander since the edit button on the older version i had to put a panel
to view it but you did not and it is in view.
May be to be on the safe side put a panel?

**Comment by DGH2112** [comment] 2019-01-06 14:13
In some instances I've used panels to get that bottom alignment (for button collections). Elsewhere I've just aligned controls alTop, alBottom or alClient to achieve the required along with AlignWithMargins = True.
Since you've said its okay now I'll close this issue.

**Closed as completed by DGH2112** 2019-01-06 14:13 UTC

**Comment by DGH2112** [comment] 2019-01-06 21:23
Just in case you are interested, now that QP is backup, this is a known unresolved issue...
[https://quality.embarcadero.com/browse/RSP-15365](https://quality.embarcadero.com/browse/RSP-15365)
